import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShoppingBag, Heart, Menu, X, ArrowLeft, Star, Sparkles, Gem, Scissors, Truck, ShieldCheck, MapPin, Phone, Mail, Plus, Check, Quote, Minus, Trash2 } from 'lucide-react';
import { useStore, Product } from '../context/StoreContext';
import LanguageSwitcher from '../components/LanguageSwitcher';

interface CartItem { id: string; qty: number; product: Product; }
const CATEGORY_IDS = ["all", "chevron", "chain", "classic", "clutch", "crossbody"] as const;
const CAT_LABELS: Record<string, string> = { all: "الكل", chevron: "شيفرون", chain: "بسلسلة", classic: "كلاسيك", clutch: "كلتش", crossbody: "كروس" };

function Navbar({ cartCount, onCart, onWish, wishCount }: any) {
  const { storeInfo } = useStore();
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <>
      <div className="bg-[#1a1410] text-[#d4b483] text-xs py-2 overflow-hidden"><div className="max-w-7xl mx-auto px-4 whitespace-nowrap">{storeInfo.announcementText}</div></div>
      <nav className="sticky top-0 z-40 bg-[#faf6ef]/95 backdrop-blur border-b border-[#b8935a]/15">
        <div className="max-w-7xl mx-auto px-4 md:px-8 h-20 flex items-center justify-between">
          <a href="#home" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full border border-[#b8935a] flex items-center justify-center overflow-hidden bg-white">
              {storeInfo.brandLogoImage ? <img src={storeInfo.brandLogoImage} className="w-full h-full object-contain p-1" /> : <span className="font-display text-[#b8935a] text-xl italic font-bold">{storeInfo.brandLogo}</span>}
            </div>
            <div><div className="font-display text-xl tracking-[0.2em] text-[#1a1410]">{storeInfo.brandName}</div><div className="text-[9px] tracking-[0.28em] text-[#b8935a] uppercase">{storeInfo.brandSub}</div></div>
          </a>
          <div className="hidden lg:flex items-center gap-8 text-sm text-[#1a1410]"><a href="#collections">المجموعات</a><a href="#shop">المتجر</a><a href="#story">قصتنا</a><a href="#craft">الحرفية</a><a href="#contact">تواصل</a></div>
          <div className="flex items-center gap-2">
            <LanguageSwitcher />
            <button onClick={onWish} className="relative w-10 h-10 flex items-center justify-center rounded-full hover:bg-[#b8935a]/10"><Heart size={18} />{wishCount>0 && <span className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-red-500 text-white text-[9px] flex items-center justify-center">{wishCount}</span>}</button>
            <button onClick={onCart} className="relative w-10 h-10 flex items-center justify-center rounded-full hover:bg-[#b8935a]/10"><ShoppingBag size={18} />{cartCount>0 && <span className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-[#b8935a] text-white text-[10px] flex items-center justify-center">{cartCount}</span>}</button>
            <button onClick={() => setMenuOpen(true)} className="lg:hidden w-10 h-10 flex items-center justify-center rounded-full hover:bg-[#b8935a]/10"><Menu size={20} /></button>
          </div>
        </div>
      </nav>
      <AnimatePresence>{menuOpen && <motion.div initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} className="fixed inset-y-0 right-0 w-72 bg-[#faf6ef] z-50 shadow-2xl p-5"><div className="flex justify-between items-center mb-6"><div className="font-display text-xl">{storeInfo.brandName}</div><button onClick={() => setMenuOpen(false)}><X /></button></div><div className="space-y-4"><a href="#collections" onClick={()=>setMenuOpen(false)} className="block">المجموعات</a><a href="#shop" onClick={()=>setMenuOpen(false)} className="block">المتجر</a><a href="#story" onClick={()=>setMenuOpen(false)} className="block">قصتنا</a><a href="#craft" onClick={()=>setMenuOpen(false)} className="block">الحرفية</a><a href="#contact" onClick={()=>setMenuOpen(false)} className="block">تواصل</a></div></motion.div>}</AnimatePresence>
    </>
  );
}

function ProductDetailsModal({ product, onClose, onAdd }: any) {
  if (!product) return null;
  return <AnimatePresence><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/60 flex items-end md:items-center justify-center p-0 md:p-4" onClick={onClose}><motion.div initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} exit={{y:80,opacity:0}} onClick={e=>e.stopPropagation()} className="bg-[#faf6ef] w-full md:max-w-4xl rounded-t-3xl md:rounded-2xl overflow-hidden shadow-2xl"><div className="grid md:grid-cols-2"><div className="bg-[#e8dcc4] min-h-[350px]"><img src={product.image} className="w-full h-full object-cover" /></div><div className="p-6 md:p-8"><div className="text-[10px] tracking-[0.3em] text-[#b8935a] uppercase mb-2">{product.nameEn}</div><h3 className="font-display text-3xl text-[#1a1410] mb-3">{product.name}</h3><div className="font-display text-2xl text-[#b8935a] mb-5">{product.price} د.م</div><div className="grid grid-cols-2 gap-3 mb-6 text-sm"><div className="bg-white rounded-lg p-3 border border-[#b8935a]/15"><div className="text-xs text-[#5c4330]/60 mb-1">اللون</div><div>{product.color}</div></div><div className="bg-white rounded-lg p-3 border border-[#b8935a]/15"><div className="text-xs text-[#5c4330]/60 mb-1">المخزون</div><div>{product.stock > 0 ? `متوفر (${product.stock})` : 'نفد المخزون'}</div></div></div><p className="text-sm text-[#5c4330] leading-loose mb-6">قطعة فنية مطرّزة يدوياً على كنفا بلاستيكية بخيوط رافيا فاخرة، مزودة بإكسسوارات معدنية أنيقة وتشطيب متقن.</p><div className="flex gap-3"><button onClick={onClose} className="px-5 py-3 border border-[#1a1410] rounded-lg">إغلاق</button><button disabled={product.stock===0} onClick={()=>onAdd(product)} className="flex-1 px-5 py-3 bg-[#1a1410] text-white rounded-lg hover:bg-[#b8935a] disabled:opacity-50">أضيفي للسلة</button></div></div></div></motion.div></motion.div></AnimatePresence>;
}

function OrderModal({ items, onClose, onSuccess }: any) {
  const { addOrder } = useStore();
  const total = items.reduce((s: number,i: CartItem)=> s + i.product.price*i.qty, 0);
  const [form, setForm] = useState({ name:'', phone:'', city:'', address:'', notes:'' });
  const [loading, setLoading] = useState(false);
  const submit = async (e:any) => { e.preventDefault(); setLoading(true); const order = await addOrder({ customerName: form.name, customerPhone: form.phone, customerCity: form.city, customerAddress: form.address, notes: form.notes, items: items.map((i:CartItem)=>({ productId:i.product.id, productName:i.product.name, productImage:i.product.image, color:i.product.color, price:i.product.price, qty:i.qty })), total }); setLoading(false); if(order) onSuccess(order.id); };
  return <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="bg-[#faf6ef] max-w-lg w-full rounded-2xl shadow-2xl overflow-hidden"><div className="p-5 border-b border-[#b8935a]/20 flex justify-between items-center"><h3 className="font-display text-xl">تأكيد الطلب</h3><button onClick={onClose}><X /></button></div><form onSubmit={submit} className="p-5 space-y-4"><input className="w-full px-4 py-3 border rounded-lg" placeholder="الاسم الكامل" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /><input className="w-full px-4 py-3 border rounded-lg" placeholder="رقم الهاتف" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required /><div className="grid grid-cols-2 gap-3"><input className="w-full px-4 py-3 border rounded-lg" placeholder="المدينة" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} required /><input className="w-full px-4 py-3 border rounded-lg" placeholder="العنوان" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required /></div><textarea className="w-full px-4 py-3 border rounded-lg h-24" placeholder="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} /><div className="bg-white border rounded-lg p-4 text-sm"><div className="mb-2 text-[#5c4330]">ملخص الطلب</div>{items.map((i:CartItem)=><div key={i.id} className="flex justify-between py-1"><span>{i.product.name} × {i.qty}</span><span>{i.product.price*i.qty} د.م</span></div>)}<div className="flex justify-between font-display text-lg mt-2 pt-2 border-t"><span>المجموع</span><span className="text-[#b8935a]">{total} د.م</span></div></div><button disabled={loading} className="w-full py-4 bg-[#1a1410] text-white rounded-lg hover:bg-[#b8935a]">{loading ? 'جاري التأكيد...' : 'تأكيد الطلب'}</button></form></div></div>;
}

export default function Website() {
  const { products, collections, testimonials, craftSteps, storeInfo, loading } = useStore();
  const [cart, setCart] = useState<CartItem[]>([]);
  const [wishlist, setWishlist] = useState<string[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [wishOpen, setWishOpen] = useState(false);
  const [selected, setSelected] = useState<Product | null>(null);
  const [orderOpen, setOrderOpen] = useState(false);
  const [orderSuccess, setOrderSuccess] = useState<string | null>(null);
  const [filter, setFilter] = useState('all');
  const filtered = filter === 'all' ? products : products.filter(p => p.category === filter);
  const addToCart = (p: Product) => setCart(prev => { const ex = prev.find(i=>i.id===p.id); return ex ? prev.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i) : [...prev,{id:p.id,qty:1,product:p}] });
  const changeQty = (id:string,d:number)=> setCart(prev => prev.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+d)}:i));
  const removeCart = (id:string)=> setCart(prev=>prev.filter(i=>i.id!==id));
  const toggleWish=(id:string)=> setWishlist(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
  if (loading) return <div className="min-h-screen bg-[#faf6ef] flex items-center justify-center"><div className="w-12 h-12 border-4 border-[#b8935a]/30 border-t-[#b8935a] rounded-full animate-spin" /></div>;
  return <div className="min-h-screen bg-[#faf6ef] text-[#1a1410]"><Navbar cartCount={cart.reduce((s,i)=>s+i.qty,0)} onCart={()=>setCartOpen(true)} onWish={()=>setWishOpen(true)} wishCount={wishlist.length} />
    <section id="home" className="py-14 md:py-20"><div className="max-w-7xl mx-auto px-4 md:px-8 grid lg:grid-cols-2 gap-10 items-center"><div><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-[#b8935a]/40 bg-white/60 mb-6"><Sparkles size={14} className="text-[#b8935a]" /><span className="text-xs tracking-[0.3em] text-[#5c4330] uppercase">{storeInfo.heroSubtitle}</span></div><h1 className="font-display text-5xl md:text-6xl lg:text-7xl leading-[1.05] mb-5 whitespace-pre-line">{storeInfo.heroTitle}</h1><p className="text-[#5c4330] text-lg leading-loose max-w-lg mb-8">{storeInfo.heroDescription}</p><a href="#shop" className="inline-flex items-center gap-3 px-8 py-4 bg-[#1a1410] text-white text-sm tracking-[0.2em] uppercase hover:bg-[#b8935a] transition">تسوّقي الآن <ArrowLeft size={16}/></a></div><div className="relative aspect-[4/5] overflow-hidden shadow-2xl"><img src={storeInfo.heroImage} className="w-full h-full object-cover" /><div className="absolute inset-4 border border-[#b8935a]/30" /></div></div></section>
    <section className="py-12 border-y border-[#b8935a]/10 bg-[#f0e8d8]/40"><div className="max-w-7xl mx-auto px-4 md:px-8 grid grid-cols-2 lg:grid-cols-4 gap-6">{[{i:Scissors,t:'تطريز يدوي 100%',d:'كل غرزة بيدٍ ماهرة'},{i:Gem,t:'قطعة فريدة',d:'تصاميم حصرية لا تتكرر'},{i:Truck,t:'شحن لجميع المغرب',d:storeInfo.shippingText},{i:ShieldCheck,t:'جودة مضمونة',d:'خيوط رافيا ثابتة الألوان'}].map((x:any)=><div key={x.t} className="flex items-start gap-3"><div className="w-12 h-12 rounded-full border border-[#b8935a]/40 flex items-center justify-center bg-white"><x.i size={20} className="text-[#b8935a]"/></div><div><div className="font-semibold text-sm">{x.t}</div><div className="text-xs text-[#5c4330] mt-0.5">{x.d}</div></div></div>)}</div></section>
    <section id="collections" className="py-20"><div className="max-w-7xl mx-auto px-4 md:px-8"><div className="flex justify-between items-end mb-10"><div><div className="text-xs tracking-[0.4em] text-[#b8935a] uppercase mb-3">— مجموعاتنا</div><h2 className="font-display text-4xl md:text-5xl">اختاري <span className="italic">قصتكِ</span></h2></div></div><div className="grid md:grid-cols-3 gap-5">{collections.map((c,i)=><a href="#shop" key={i} className="group relative aspect-[3/4] overflow-hidden block"><img src={c.img} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><div className="absolute bottom-6 right-6 left-6 text-white"><h3 className="font-display text-2xl mb-1">{c.title}</h3><div className="text-sm opacity-80">{c.count} قطعة</div></div></a>)}</div></div></section>
    <section id="shop" className="py-20 bg-[#f0e8d8]/30"><div className="max-w-7xl mx-auto px-4 md:px-8"><div className="text-center mb-10"><div className="text-xs tracking-[0.4em] text-[#b8935a] uppercase mb-3">— متجرنا</div><h2 className="font-display text-4xl md:text-5xl">قطعٌ <span className="italic">استثنائية</span></h2></div><div className="flex flex-wrap justify-center gap-2 mb-10">{CATEGORY_IDS.map(cat=><button key={cat} onClick={()=>setFilter(cat)} className={`px-5 py-2.5 text-xs tracking-[0.18em] uppercase border-2 transition ${filter===cat?'bg-[#1a1410] text-white border-[#1a1410]':'border-[#2b1d12]/20 hover:border-[#b8935a]'}`}>{CAT_LABELS[cat]}</button>)}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">{filtered.map(p=><div key={p.id} className="group bg-white rounded-lg overflow-hidden shadow-sm hover:shadow-xl transition"><div className="relative aspect-[4/5] overflow-hidden"><button className="w-full h-full text-start" onClick={()=>setSelected(p)}><img src={p.image} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"/></button>{p.tag&&<div className="absolute top-3 right-3 bg-[#1a1410] text-white text-[9px] px-2.5 py-1.5">{p.tag}</div>}<button onClick={()=>toggleWish(p.id)} className={`absolute top-3 left-3 w-9 h-9 rounded-full flex items-center justify-center ${wishlist.includes(p.id)?'bg-red-500 text-white':'bg-white/90 text-[#2b1d12]'}`}><Heart size={15} fill={wishlist.includes(p.id)?'currentColor':'none'} /></button>{p.stock>0 && <div className="absolute bottom-0 inset-x-0 p-3 translate-y-full group-hover:translate-y-0 transition-transform"><button onClick={()=>addToCart(p)} className="w-full py-3 bg-[#faf6ef] text-[#1a1410] text-xs tracking-[0.2em] uppercase flex items-center justify-center gap-2 hover:bg-[#b8935a] hover:text-white"><Plus size={14}/> أضيفي للسلة</button></div>}</div><div className="p-4"><div className="text-[9px] tracking-[0.28em] text-[#b8935a] uppercase mb-1">{p.nameEn}</div><h3 className="font-display text-lg">{p.name}</h3><div className="text-xs text-[#5c4330] mb-2">{p.color}</div><div className="font-display text-[#b8935a]">{p.price} {storeInfo.currencySymbol}</div>{p.oldPrice && <div className="text-xs text-[#5c4330]/50 line-through">{p.oldPrice}</div>}</div></div>)}</div></div></section>
    <section id="story" className="py-24 bg-[#1a1410] text-[#faf6ef]"><div className="max-w-7xl mx-auto px-4 md:px-8 grid lg:grid-cols-2 gap-14 items-center"><div className="relative"><img src={craftSteps[0]?.img || storeInfo.heroImage} className="w-full aspect-[4/5] object-cover" /><div className="absolute -top-5 -left-5 bg-[#b8935a] text-[#1a1410] p-5"><div className="font-display text-3xl">Est.</div><div className="text-xs tracking-[0.2em] mt-1">{storeInfo.storyYear} · {storeInfo.storyCity}</div></div></div><div><div className="text-xs tracking-[0.4em] text-[#d4b483] uppercase mb-4">— قصتنا</div><h2 className="font-display text-4xl md:text-5xl leading-tight mb-6 whitespace-pre-line">{storeInfo.storyTitle}</h2><p className="text-[#d4b483]/80 leading-loose">{storeInfo.storyDescription}</p></div></div></section>
    <section id="craft" className="py-20"><div className="max-w-7xl mx-auto px-4 md:px-8"><div className="text-center mb-12"><div className="text-xs tracking-[0.4em] text-[#b8935a] uppercase mb-3">— رحلة الصنع</div><h2 className="font-display text-4xl md:text-5xl">أربعُ مراحل، <span className="italic">قطعةٌ فريدة</span></h2></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">{craftSteps.map((step,i)=><div key={i}><div className="relative aspect-[4/5] overflow-hidden mb-4"><img src={step.img} className="w-full h-full object-cover"/><div className="absolute top-3 right-3 w-11 h-11 rounded-full bg-white flex items-center justify-center"><span className="font-display text-[#b8935a]">{step.num}</span></div></div><h3 className="font-display text-xl mb-2">{step.title}</h3><p className="text-sm text-[#5c4330] leading-relaxed">{step.desc}</p></div>)}</div></div></section>
    <section className="py-20 bg-[#f0e8d8]/50"><div className="max-w-7xl mx-auto px-4 md:px-8"><div className="text-center mb-12"><div className="text-xs tracking-[0.4em] text-[#b8935a] uppercase mb-3">— آراء عميلاتنا</div><h2 className="font-display text-4xl md:text-5xl">كلماتٌ <span className="italic">من القلب</span></h2></div><div className="grid md:grid-cols-3 gap-6">{testimonials.map((t,i)=><div key={i} className="bg-white rounded-xl p-6 shadow-sm border border-[#b8935a]/10"><Quote size={28} className="text-[#b8935a]/30 mb-4"/><p className="text-[#5c4330] leading-loose mb-4">{t.text}</p><div className="flex items-center justify-between"><div><div className="font-semibold">{t.name}</div><div className="text-xs text-[#5c4330]">{t.role}</div></div><div className="flex gap-0.5">{Array.from({length:t.rating}).map((_,j)=><Star key={j} size={12} className="fill-[#b8935a] text-[#b8935a]"/>)}</div></div></div>)}</div></div></section>
    <section className="py-16"><div className="max-w-7xl mx-auto px-4 md:px-8 text-center mb-8"><div className="text-xs tracking-[0.4em] text-[#b8935a] uppercase mb-3">— تابعينا</div><h2 className="font-display text-3xl md:text-4xl">@{storeInfo.instagram}</h2></div><div className="grid grid-cols-3 md:grid-cols-6 gap-1.5 max-w-5xl mx-auto px-4">{products.slice(0,6).map((p)=><a key={p.id} href="#shop" className="aspect-square overflow-hidden"><img src={p.image} className="w-full h-full object-cover"/></a>)}</div></section>
    <section className="py-20 bg-[#1a1410] text-white"><div className="max-w-2xl mx-auto px-4 text-center"><Sparkles className="mx-auto text-[#d4b483] mb-5" size={26}/><h2 className="font-display text-3xl md:text-4xl mb-4">انضمّي إلى عالم <span className="italic text-[#d4b483]">{storeInfo.brandName}</span></h2><p className="text-[#d4b483]/75 mb-8">اشتركي في نشرتنا للحصول على العروض الحصرية والمجموعات الجديدة قبل الجميع.</p><div className="flex flex-col sm:flex-row gap-3 max-w-lg mx-auto"><input className="flex-1 bg-transparent border border-[#b8935a]/40 px-5 py-3.5 rounded-sm" placeholder="بريدكِ الإلكتروني"/><button className="bg-[#b8935a] text-[#1a1410] px-7 py-3.5 text-xs tracking-[0.22em] uppercase">اشتركي</button></div></div></section>
    <footer id="contact" className="bg-[#110c08] text-[#d4b483] pt-16 pb-8"><div className="max-w-7xl mx-auto px-4 md:px-8"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-10 mb-14"><div><div className="flex items-center gap-2.5 mb-5"><div className="w-10 h-10 rounded-full border border-[#b8935a] flex items-center justify-center overflow-hidden bg-white">{storeInfo.brandLogoImage ? <img src={storeInfo.brandLogoImage} className="w-full h-full object-contain p-1" /> : <span className="font-display text-[#b8935a] text-xl italic font-bold">{storeInfo.brandLogo}</span>}</div><div><div className="font-display text-xl tracking-[0.2em] text-[#faf6ef]">{storeInfo.brandName}</div><div className="text-[8px] tracking-[0.25em] text-[#b8935a] uppercase">{storeInfo.brandSub}</div></div></div><p className="text-sm leading-relaxed text-[#d4b483]/75">{storeInfo.footerDescription}</p></div><div><h4 className="font-display text-base text-[#faf6ef] mb-4">المتجر</h4><ul className="space-y-2 text-sm"><li><a href="#shop">جميع المنتجات</a></li><li><a href="#collections">المجموعات</a></li></ul></div><div><h4 className="font-display text-base text-[#faf6ef] mb-4">خدمة العملاء</h4><ul className="space-y-2 text-sm"><li><a href="#contact">تواصلي معنا</a></li><li><a href="#">الشحن والتوصيل</a></li></ul></div><div><h4 className="font-display text-base text-[#faf6ef] mb-4">تواصلي معنا</h4><ul className="space-y-3 text-sm"><li className="flex gap-2"><Phone size={15} className="text-[#b8935a]"/><span>{storeInfo.phone}</span></li><li className="flex gap-2"><Mail size={15} className="text-[#b8935a]"/><span>{storeInfo.email}</span></li><li className="flex gap-2"><MapPin size={15} className="text-[#b8935a]"/><span>{storeInfo.address}</span></li></ul></div></div><div className="pt-6 border-t border-[#b8935a]/15 text-xs text-[#d4b483]/50 text-center">© 2026 {storeInfo.brandName}. جميع الحقوق محفوظة.</div></div></footer>
    <ProductDetailsModal product={selected} onClose={()=>setSelected(null)} onAdd={(p:Product)=>{addToCart(p); setSelected(null);}} />
    {orderOpen && <OrderModal items={cart} onClose={()=>setOrderOpen(false)} onSuccess={(id:string)=>{setOrderOpen(false); setOrderSuccess(id); setCart([]);}} />}
    {orderSuccess && <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="bg-[#faf6ef] max-w-md w-full rounded-2xl p-8 text-center"><div className="w-20 h-20 rounded-full bg-green-100 text-green-600 flex items-center justify-center mx-auto mb-4"><Check size={36}/></div><h3 className="font-display text-2xl mb-2">تم تأكيد طلبكِ!</h3><p className="mb-2">رقم طلبكِ: <strong className="text-[#b8935a]">{orderSuccess}</strong></p><button onClick={()=>setOrderSuccess(null)} className="mt-5 px-6 py-3 bg-[#1a1410] text-white rounded-lg">حسناً</button></div></div>}
    <AnimatePresence>{cartOpen && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/40" onClick={()=>setCartOpen(false)}><motion.div initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} onClick={e=>e.stopPropagation()} className="absolute top-0 right-0 bottom-0 w-full max-w-sm bg-[#faf6ef] shadow-2xl flex flex-col"><div className="p-5 border-b border-[#b8935a]/20 flex justify-between items-center"><h3 className="font-display text-xl">السلّة</h3><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="flex-1 overflow-y-auto p-4">{cart.length===0?<div className="text-center py-20 text-[#5c4330]">سلّتكِ فارغة</div>:<div className="space-y-3">{cart.map(i=><div key={i.id} className="flex gap-3 bg-white p-3 rounded-xl border"><img src={i.product.image} className="w-[72px] h-[80px] object-cover rounded-lg"/><div className="flex-1"><div className="font-display text-sm">{i.product.name}</div><div className="text-xs text-[#5c4330]">{i.product.color}</div><div className="flex items-center justify-between mt-2"><div className="flex items-center gap-2 border rounded-full px-2"><button onClick={()=>changeQty(i.id,-1)}><Minus size={12}/></button><span className="text-xs">{i.qty}</span><button onClick={()=>changeQty(i.id,1)}><Plus size={12}/></button></div><button onClick={()=>removeCart(i.id)} className="text-red-500"><Trash2 size={13}/></button></div></div></div>)}</div>}</div>{cart.length>0&&<div className="p-4 border-t border-[#b8935a]/20"><div className="flex justify-between mb-3"><span>المجموع</span><span className="font-display text-xl text-[#b8935a]">{cart.reduce((s,i)=>s+i.product.price*i.qty,0)} د.م</span></div><button onClick={()=>{setCartOpen(false); setOrderOpen(true)}} className="w-full py-4 bg-[#1a1410] text-white rounded-lg hover:bg-[#b8935a]">إتمام الطلب</button></div>}</motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{wishOpen && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/40" onClick={()=>setWishOpen(false)}><motion.div initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} onClick={e=>e.stopPropagation()} className="absolute top-0 right-0 bottom-0 w-full max-w-sm bg-[#faf6ef] shadow-2xl"><div className="p-5 border-b border-[#b8935a]/20 flex justify-between items-center"><h3 className="font-display text-xl">المفضلة</h3><button onClick={()=>setWishOpen(false)}><X/></button></div><div className="p-4 space-y-3 overflow-y-auto h-full">{products.filter(p=>wishlist.includes(p.id)).length===0?<div className="text-center py-20 text-[#5c4330]">لا توجد منتجات في المفضلة</div>:products.filter(p=>wishlist.includes(p.id)).map(p=><div key={p.id} className="flex gap-3 bg-white p-3 rounded-xl border"><img src={p.image} className="w-[72px] h-[80px] object-cover rounded-lg"/><div className="flex-1"><div className="font-display text-sm">{p.name}</div><div className="text-xs text-[#5c4330] mb-2">{p.color}</div><div className="font-display text-[#b8935a]">{p.price} د.م</div><div className="flex gap-2 mt-2"><button onClick={()=>{addToCart(p); setWishOpen(false)}} className="flex-1 py-2 bg-[#1a1410] text-white text-xs rounded">أضيفي للسلة</button><button onClick={()=>toggleWish(p.id)} className="p-2 text-red-500"><Trash2 size={14}/></button></div></div></div>)}</div></motion.div></motion.div>}</AnimatePresence>
    <a href={`https://wa.me/${storeInfo.whatsapp}`} className="fixed bottom-6 left-4 z-40 w-14 h-14 rounded-full bg-[#25D366] text-white flex items-center justify-center shadow-xl"><svg viewBox="0 0 24 24" className="w-7 h-7 fill-current"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.297-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.67-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.693.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884"/></svg></a>
  </div>;
}
